### ISSUE TITLE
Need for editing of target text in anonymization mode

### ISSUE THREAD

**Issue by elenavolodina** [spraakbanken/swell-editor#85] opened 2018-08-21 11:09 UTC
Consider example "omkriga 3 minuter.Hallund har..." where "minuter.Halland" are not correctly segmented, and thus during anonymization both tokens will be removed and replaced with a placeholder for "region". This is another proof that we need to have an option to edit target text even during anonymization, alongside with wrongly spelled ages (see previous issue). 

I am duplicating this issue to swell-kiosk/CJ as well.

**Comment by cajosc** [comment] 2018-09-20 20:01
Duplicate of #89.

**Closed by cajosc** 2018-09-20 20:01 UTC
Labels: anonymization
